# Site settings
title: Samira Hajizadeh
email: SamiraHajizadeh01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a description for my personal webpage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: user
github_username: SamiraHajizadeh

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
